# Custom Language File for Launcher Customizer

[ejs.app]
title = "SR그라운드"

[ejs.landing]
mediaGitHubURL = "https://github.com/SRRMFKDNSEM/SR-GROUND"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/ZmPe9F9A49"

[ejs.settings]
sourceGithubLink = "https://github.com/SRRMFKDNSEM/SR-GROUND"
supportLink = "https://github.com/SRRMFKDNSEM/SR-GROUND/issues"

[ejs.welcome]
welcomeHeader = "SR그라운드에 오신 것을 환영합니다."
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
